---
plugin: aws_ec2
regions:
  - us-east-1
keyed_groups:
  - key: tags.Owner
    prefix: tag
filters:
  instance-state-name : running
  instance-id: 
    - i-09b1c4e9fa1bd719b
    - i-0df377a0fa65ed25a
compose:
  ansible_host: public_ip_address
